eth2stats_display_name: ğŸ Lighthouse ğŸ
eth2stats_api_addr: "http://localhost:{{beacon_rpc_port}}"
eth2stats_metrics_url: "http://localhost:{{beacon_metrics_port}}/metrics"
eth2stats_beacon_type: v1
