beacon_image_name: pegasyseng/teku:develop

validators_config_file: "validators_config.yml"

# Debug logging spams a ton of http data every eth2stats call (every second).
beacon_start_args: >
  --logging=INFO
  --network=altona
  --data-path="{{beacon_container_dir}}"
  --p2p-advertised-ip={{public_ip_address}}
  --p2p-advertised-port=9000
  --p2p-port=9000
  --p2p-discovery-enabled=true
  --p2p-peer-lower-bound=30
  --p2p-peer-upper-bound=50
  --log-destination=CONSOLE
  --eth1-endpoint={{eth1_endpoint.http}}
  --rest-api-enabled=true --rest-api-interface=0.0.0.0 --rest-api-port=4000
  --metrics-enabled --metrics-interface=0.0.0.0 --metrics-port=8080
  --metrics-host-allowlist="*"
  --rest-api-host-allowlist="*"
  --p2p-discovery-bootnodes="enr:-LK4QLkbbq7xuRa_EnWd_kc0TkQk0pd0B0cZYR5LvBsncFQBDyPbGdy8d24TzRVeK7ZWwM5_2EcSJK223f8TYUOQYfwBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD9yjmwAAABIf__________gmlkgnY0gmlwhAPsjtOJc2VjcDI1NmsxoQJNw_aZgWXl2SstD--WAjooGudjWLjEbbCIddJuEPxzWYN0Y3CCIyiDdWRwgiMo,enr:-LK4QHy-glnxN1WTk5f6d7-xXwy_UKJLs5k7p_S4KRY9I925KTzW_kQLjfFriIpH0de7kygBwrSl726ukq9_OG_sgKMCh2F0dG5ldHOIUjEAIQEAFMiEZXRoMpD9yjmwAAABIf__________gmlkgnY0gmlwhBLmhrCJc2VjcDI1NmsxoQNlU7gT0HUvpLA41n-P5GrCgjwMwtG02YsRRO0lAmpmBYN0Y3CCIyiDdWRwgiMo,enr:-LK4QDz0n0vpyOpuStB8e22h9ayHVcvmN7o0trC7eC0DnZV9GYGzK5uKv7WlzpMQM2nDTG43DWvF_DZYwJOZCbF4iCQBh2F0dG5ldHOI__________-EZXRoMpD9yjmwAAABIf__________gmlkgnY0gmlwhBKN136Jc2VjcDI1NmsxoQP5gcOUcaruHuMuTv8ht7ZEawp3iih7CmeLqcoY1hxOnoN0Y3CCIyiDdWRwgiMo"
  {% if validator_enabled %}
  --validators-graffiti="{{ validator_graffiti | default('@protolambda') }}"
  --config-file="{{validator_container_dir}}/{{validators_config_file}}"
  {% endif %}

beacon_env:
  JAVA_OPTS: "-Xmx2800m"

keystores_container_dir: "{{beacon_container_dir}}/keys"
secrets_container_dir: "{{beacon_container_dir}}/secrets"

keystores_host_dir: "{{beacon_host_dir}}/keys"
secrets_host_dir: "{{beacon_host_dir}}/secrets"

validator_config_host_path: "{{ validator_host_dir }}/{{validators_config_file}}"
