# without "http://" since GRPC is used.
eth2stats_display_name: ğŸ Prysm ğŸ
eth2stats_api_addr: "localhost:{{beacon_grpc_port}}"
eth2stats_metrics_url: "http://localhost:{{beacon_metrics_port}}/metrics"
eth2stats_beacon_type: prysm
