eth2stats_display_name: ğŸ Lodestar ğŸ
eth2stats_api_addr: "http://localhost:{{beacon_rpc_port}}"
eth2stats_metrics_url: "http://localhost:{{beacon_metrics_port}}/metrics"
# Lodestar uses the v1 standardized Eth2 API for eth2stats.
eth2stats_beacon_type: v1
